//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppPdf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleAppPdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to �DSIG��F���GDEF��8RT	�GPOS[�\@m4GSUB&amp;G���ttHVAR������OS/2M)1�`STAT�f(�|�avar *��(cmap�Ż�xcvt 9�%`)`�fpgmoĢ��ufvar%�^��8�gasp	RHglyf��6�0��gvar՞�v�$��head�6��6hhea_
        ///x�$hmtx;�h        ///loca:&amp;��*D�maxp��� meta��Q��HnameI�K�Gt
        ///�post��2R( prepgYL&apos;UIј_&lt;��~Ɛ֚%`�������Z	J�����DD�	^/��u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bahnschrift {
            get {
                return ResourceManager.GetString("Bahnschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FFTMdP��$GDEFx�@4GPOSH.Jp�tJGSUB�ؓS���OS/2�&quot;f��Vcmap����cvt 	��&lt;.fpgm�.�P	bgasp�glyf9���@head����,6hhea�d$hmtxh�p��loca�c��lVmaxp�
        ///X� name�l���post�f�� prep��(��2$Yq_&lt;�	̏|�̐�`�E�@	o	�����������a_$2j�	b!�3�3��f��@Knewt         ///�	���	�O��D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oswald_Bold {
            get {
                return ResourceManager.GetString("Oswald-Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FFTMe%��GDEF(��(GPOS����,
        ///rGSUB�����$OS/2�%a0�Vcmapu����ncvt {��.fpgm�.��	bgasp��glyfN�&amp;�T�thead�+�*,6hhea�gd$hmtxs�x�loca�
        ///�Dmaxp�
        ///�� name�������post�m2�� prep��(X�=n-_&lt;�	̏|̐�`�o��~	(	���b����~����&quot;0j�	b�,3�3��f�o@Knewt �	���	�O��D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oswald_Light {
            get {
                return ResourceManager.GetString("Oswald-Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FFTMe%���GDEF(��(GPOS����@�GSUB�����$OS/2��c��Vcmap��ҫ�ncvt ���.fpgm�.��	bgasp��glyfro��`�lhead�V��,6hhea��d$hmtxv��loca����Hmaxp�
        ///�� name���Y��post�� prep��(`�{+|$_&lt;�	̏|�̐�a�-�t�	x	����������w}(6j�	b�3�3��f�o@Knewt@ �	���	�O��D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oswald_Regular {
            get {
                return ResourceManager.GetString("Oswald-Regular", resourceCulture);
            }
        }
    }
}
